---
- name: Yolo E-commerce Configuration
  hosts: all
  become: true
  collections:
    - community.docker

  vars_files:
    - group_vars/web.yaml

  roles:
    - { role: database, tags: ['database'] }
    - { role: backend, tags: ['backend'] }
    - { role: frontend, tags: ['frontend'] }
