---
- name: Provision Infrastructure and Deploy YOLO E-commerce App
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - group_vars/web.yaml

- name: Configure and Deploy YOLO E-commerce App
  hosts: all
  become: true
  gather_facts: false

  vars_files:
    - group_vars/web.yaml

  roles:
    - { role: database, tags: ['database'] }
    - { role: backend, tags: ['backend'] }
    - { role: frontend, tags: ['frontend'] }
    - { role: terraform, tags: ['terraform'] }
