---
- name: Install prerequisites for Backend role
  block:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

- name: Clone Yolo repo for Backend
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: master

- name: Set Docker Compose directory
  set_fact:
    docker_compose_directory: "{{ playbook_dir }}"

- name: Start Backend container using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_dirdocker_compose_directory }}"
    state: present
    build: always
    pull: always
