---
- name: Install prerequisites for Backend role
  block:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

- name: Clone Yolo repo for Backend
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: master

- name: Start Backend container
  community.docker.docker_container:
    name: yolo-backend
    image: hottensiahnyanjui/hottensiah-yolo-backend:v1.0.0
    state: started
    restart_policy: no
    ports:
      - "5000:5000"
    env:
      MONGODB_URI: mongodb://app-ip-mongo:27017/yolomy
    networks:
      - name: app-net
