---
- name: Install prerequisites for Frontend role
  block:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install Git
      apt:
        name: git
        state: present

- name: Clone Yolo repo for Frontend
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: master

- name: Set Docker Compose directory
  set_fact:
    docker_compose_directory: "{{ playbook_dir }}"

- name: Start application using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
    restarted: smart
    remove_orphans: yes
