---
- name: Install prerequisites for Database
  block:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

- name: Clone Yolo repo for Database
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: main

- name: Start MongoDB container
  community.docker.docker_container:
    name: app-mongo
    image: mongo
    state: started
    restart_policy: always
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - name: app-net
